Service_keyboard = "{\"one_time_keyboard\": true, \"keyboard\": [[\"Search image\"], [\"Search wiki\"], [\"Search gamewith\"]]}"

Element_keyboard = "{\"one_time_keyboard\": true, \"keyboard\": [[\"Fire\"], [\"Water\"], [\"Earth\"], [\"Wind\"], [\"Light\"], [\"Dark\"], [\"Back\"]]}"

Character_keyboard = {
    'Fire':  "{\"one_time_keyboard\": true, \"keyboard\": [[\"Reset\"], [\"Back\"], [\"Yuel\"], [\"Magisa\"], [\"Agielba\"], [\"Zeta\"], [\"Clarisse\"], [\"Percival\"], [\"Ghandagoza\"], [\"Heles\"], [\"Metera(Fire)\"], [\"Zahlhamelina\"], [\"Aoidos\"], [\"Aliza\"], [\"Societte(Fire)\"], [\"Anthuria\"], [\"Grea\"]]}",
    'Water': "{\"one_time_keyboard\": true, \"keyboard\": [[\"Reset\"], [\"Back\"], [\"Altair\"], [\"Lily\"], [\"Charlotta\"], [\"Lancelot\"], [\"Societte\"], [\"Silva\"], [\"Yodarha\"], [\"Lilele\"], [\"Yngwie\"], [\"Chat Noir\"], [\"Romeo\"], [\"Izmir\"], [\"Lady Katapillar and Vira\"], [\"Vane\"], [\"Anne\"], [\"Yuel(Water)\"]]}",
    'Earth': "{\"one_time_keyboard\": true, \"keyboard\": [[\"Reset\"], [\"Back\"], [\"Aletheia\"], [\"Cagliostro\"], [\"Arulumaya\"], [\"Melleau\"], [\"Sara\"], [\"Siegfried\"], [\"Eustace\"], [\"Catherine\"], [\"Nemone\"], [\"Hallessena\"], [\"Ayer\"], [\"Razia\"], [\"De La Fille(Earth)\"], [\"Yggdrasil\"], [\"Vaseraga(Earth)\"], [\"Ilza\"]]}",
    'Wind':  "{\"one_time_keyboard\": true, \"keyboard\": [[\"Reset\"], [\"Back\"], [\"Gawain\"], [\"Nezahualpilli\"], [\"Metera\"], [\"Lennah\"], [\"Carmelina\"], [\"Petra\"], [\"Arriet\"], [\"Feena\"], [\"Korwa\"], [\"Melissabelle\"], [\"Yuisis\"], [\"Scathacha\"], [\"Lancelot(Wind)\"]]}",
    'Light': "{\"one_time_keyboard\": true, \"keyboard\": [[\"Reset\"], [\"Back\"], [\"De La Fille\"], [\"Sarunan\"], [\"Seruel\"], [\"Sophia\"], [\"Jeanne d\'Arc\"], [\"Albert\"], [\"Amira\"], [\"Ferry\"], [\"Rosamia\"], [\"Juliet\"], [\"Clarisse(Light)\"], [\"Baotorda\"], [\"Dorothy and Claudia\"]]}",
    'Dark':  "{\"one_time_keyboard\": true, \"keyboard\": [[\"Reset\"], [\"Back\"], [\"Lady Grey\"], [\"Cerberus\"], [\"Vaseraga\"], [\"Vira\"], [\"Sarunan(Dark)\"], [\"Vania\"], [\"Narmaya\"], [\"Beatrix\"], [\"Forte\"], [\"Jeanne d\'Arc(Dark)\"], [\"Veight\"], [\"Marquiares\"], [\"Zeta(Dark)\"], [\"Cagliostro\"], [\"Azazel\"]]}"
}

Level_keyboard = "{\"one_time_keyboard\": true, \"keyboard\": [[\"Reset\"], [\"Back\"], [[\"%E2%98%85+1\"], [\"%E2%98%85+3\"]]}"

Element_list = ['Fire', 'Water', 'Earth', 'Wind', 'Light', 'Dark']

Character_list = [
    'Yuel',
    'Magisa',
    'Agielba',
    'Zeta',
    'Clarisse',
    'Percival',
    'Ghandagoza',
    'Heles',
    'Metera(Fire)',
    'Zahlhamelina',
    'Aoidos',
    'Aliza',
    'Societte(Fire)',
    'Anthuria',
    'Grea',

    'Altair',
    'Lily',
    'Charlotta',
    'Lancelot',
    'Societte',
    'Silva',
    'Yodarha',
    'Lilele',
    'Yngwie',
    'Chat Noir',
    'Romeo',
    'Izmir',
    'Lady Katapillar and Vira',
    'Vane',
    'Anne',
    'Yuel(Water)',

    'Aletheia',
    'Cagliostro',
    'Arulumaya',
    'Melleau',
    'Sara',
    'Siegfried',
    'Eustace',
    'Catherine',
    'Nemone',
    'Hallessena',
    'Ayer',
    'Razia',
    'De La Fille(Earth)',
    'Yggdrasil',
    'Vaseraga(Earth)',
    'Ilza',

    'Gawain',
    'Nezahualpilli',
    'Metera',
    'Lennah',
    'Carmelina',
    'Petra',
    'Arriet',
    'Feena',
    'Korwa',
    'Melissabelle',
    'Yuisis',
    'Scathacha',
    'Lancelot(Wind)',

    'De La Fille',
    'Sarunan',
    'Seruel',
    'Sophia',
    'Jeanne d\'Arc',
    'Albert',
    'Amira',
    'Ferry',
    'Rosamia',
    'Juliet',
    'Clarisse(Light)',
    'Baotorda',
    'Dorothy and Claudia',

    'Lady Grey',
    'Cerberus',
    'Vaseraga',
    'Vira',
    'Sarunan(Dark',
    'Vania',
    'Narmaya',
    'Beatrix',
    'Forte',
    'Jeanne d\'Arc(Dark)',
    'Veight',
    'Marquiares',
    'Zeta(Dark)',
    'Cagliostro',
    'Azazel'
]

Character_id = {
    'Yuel': '3040006000'
    'Magisa',
    'Agielba',
    'Zeta',
    'Clarisse',
    'Percival',
    'Ghandagoza',
    'Heles',
    'Metera(Fire)',
    'Zahlhamelina',
    'Aoidos',
    'Aliza',
    'Societte(Fire)',
    'Anthuria',
    'Grea',

    'Altair': '3040001000'
    'Lily',
    'Charlotta',
    'Lancelot',
    'Societte',
    'Silva',
    'Yodarha',
    'Lilele',
    'Yngwie',
    'Chat Noir',
    'Romeo',
    'Izmir',
    'Lady Katapillar and Vira',
    'Vane',
    'Anne',
    'Yuel(Water)',

    'Aletheia': '3040002000'
    'Cagliostro',
    'Arulumaya',
    'Melleau',
    'Sara',
    'Siegfried',
    'Eustace',
    'Catherine',
    'Nemone',
    'Hallessena',
    'Ayer',
    'Razia',
    'De La Fille(Earth)',
    'Yggdrasil',
    'Vaseraga(Earth)',
    'Ilza',

    'Gawain': '3040000000'
    'Nezahualpilli',
    'Metera',
    'Lennah',
    'Carmelina',
    'Petra',
    'Arriet',
    'Feena',
    'Korwa',
    'Melissabelle',
    'Yuisis',
    'Scathacha',
    'Lancelot(Wind)',

    'De La Fille': '3040004000'
    'Sarunan',
    'Seruel',
    'Sophia',
    'Jeanne d\'Arc',
    'Albert',
    'Amira',
    'Ferry',
    'Rosamia',
    'Juliet',
    'Clarisse(Light)',
    'Baotorda',
    'Dorothy and Claudia',

    'Lady Grey': '3040005000'
    'Cerberus',
    'Vaseraga',
    'Vira',
    'Sarunan(Dark',
    'Vania',
    'Narmaya',
    'Beatrix',
    'Forte',
    'Jeanne d\'Arc(Dark)',
    'Veight',
    'Marquiares',
    'Zeta(Dark)',
    'Cagliostro',
    'Azazel'
}

Gamewith_id = {
    'Yuel',
    'Magisa',
    'Agielba',
    'Zeta',
    'Clarisse',
    'Percival',
    'Ghandagoza',
    'Heles',
    'Metera(Fire)',
    'Zahlhamelina',
    'Aoidos',
    'Aliza',
    'Societte(Fire)',
    'Anthuria',
    'Grea',

    'Altair',
    'Lily',
    'Charlotta',
    'Lancelot',
    'Societte',
    'Silva',
    'Yodarha',
    'Lilele',
    'Yngwie',
    'Chat Noir',
    'Romeo',
    'Izmir',
    'Lady Katapillar and Vira',
    'Vane',
    'Anne',
    'Yuel(Water)',

    'Aletheia',
    'Cagliostro',
    'Arulumaya',
    'Melleau',
    'Sara',
    'Siegfried',
    'Eustace',
    'Catherine',
    'Nemone',
    'Hallessena',
    'Ayer',
    'Razia',
    'De La Fille(Earth)',
    'Yggdrasil',
    'Vaseraga(Earth)',
    'Ilza',

    'Gawain',
    'Nezahualpilli',
    'Metera',
    'Lennah',
    'Carmelina',
    'Petra',
    'Arriet',
    'Feena',
    'Korwa',
    'Melissabelle',
    'Yuisis',
    'Scathacha',
    'Lancelot(Wind)',

    'De La Fille',
    'Sarunan',
    'Seruel',
    'Sophia',
    'Jeanne d\'Arc',
    'Albert',
    'Amira',
    'Ferry',
    'Rosamia',
    'Juliet',
    'Clarisse(Light)',
    'Baotorda',
    'Dorothy and Claudia',

    'Lady Grey',
    'Cerberus',
    'Vaseraga',
    'Vira',
    'Sarunan(Dark',
    'Vania',
    'Narmaya',
    'Beatrix',
    'Forte',
    'Jeanne d\'Arc(Dark)',
    'Veight',
    'Marquiares',
    'Zeta(Dark)',
    'Cagliostro',
    'Azazel'
}
